// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHvervZmVIOTxCXuyOO1K515vePNNuHRo',
    appId: '1:157523900176:web:90431d9cd427f001c5d795',
    messagingSenderId: '157523900176',
    projectId: 'connect-pharma-f676c',
    authDomain: 'connect-pharma-f676c.firebaseapp.com',
    storageBucket: 'connect-pharma-f676c.firebasestorage.app',
    measurementId: 'G-QTNF8P8WQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVhqo-EIx-Yv0BdDSKsajH-A87k39ndWE',
    appId: '1:157523900176:android:b2e3bd6725d0e63dc5d795',
    messagingSenderId: '157523900176',
    projectId: 'connect-pharma-f676c',
    storageBucket: 'connect-pharma-f676c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtCcNXT7P9lQaFpv7wXy5DkpKHGJ-kyr4',
    appId: '1:157523900176:ios:eb9585fb8b7e6d74c5d795',
    messagingSenderId: '157523900176',
    projectId: 'connect-pharma-f676c',
    storageBucket: 'connect-pharma-f676c.firebasestorage.app',
    iosBundleId: 'com.example.connectPharma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtCcNXT7P9lQaFpv7wXy5DkpKHGJ-kyr4',
    appId: '1:157523900176:ios:eb9585fb8b7e6d74c5d795',
    messagingSenderId: '157523900176',
    projectId: 'connect-pharma-f676c',
    storageBucket: 'connect-pharma-f676c.firebasestorage.app',
    iosBundleId: 'com.example.connectPharma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHvervZmVIOTxCXuyOO1K515vePNNuHRo',
    appId: '1:157523900176:web:fff16f2d696e42edc5d795',
    messagingSenderId: '157523900176',
    projectId: 'connect-pharma-f676c',
    authDomain: 'connect-pharma-f676c.firebaseapp.com',
    storageBucket: 'connect-pharma-f676c.firebasestorage.app',
    measurementId: 'G-RC9MK71ZX5',
  );

}
