import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:connect_pharma/screens/WelcomeScreen.dart';
import 'screens/RoleSelectionScreen.dart';
import 'screens/SignUpScreen.dart';
import 'screens/LoginScreen.dart';
import 'screens/HomeScreen.dart';
import 'services/auth_service.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI (see note)
import 'dart:developer' as developer;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  try {
    developer.log('Firebase options projectId: ${DefaultFirebaseOptions.currentPlatform.projectId}');
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    developer.log('Firebase initialized. apps: ${Firebase.apps.map((e) => e.name).toList()}');
  } catch (e, st) {
    developer.log('Firebase.initializeApp failed: $e\n$st', level: 1000);
    // Optionally show a user-facing error by running app and presenting message.
  }
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Connect-Pharma',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        textTheme: GoogleFonts.interTextTheme(Theme.of(context).textTheme),
      ),
      initialRoute: '/',
      routes: {
        '/': (_) => const WelcomeScreen(),
        '/roles': (_) => const RoleSelectionScreen(),
        '/signup': (_) => const SignUpScreen(),
        '/login': (_) => const LoginScreen(),
        '/home': (_) => const HomeScreen(),
      },
    );
  }
}
